#MySql Configuration
spring.datasource.name = coursemanagement
spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USR_NAME}
spring.datasource.password = ${DB_PWD}
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

#Hibernate Config
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

#JWT Config
jwt.TokenExpiry = 30
jwt.SecretKey = TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

#AWS Config
aws.accessKey = ${AWS_ACCESS_KEY}
aws.secretKey = ${AWS_SECRET_KEY}
aws.bucket.name = ${AWS_BUCKET_KEY}

#Twilio Config
twilio.account.sid = ${TWILIO_SID}
twilio.auth.token = ${TWILIO_TOKEN}
twilio.phone.number = ${TWILIO_NUMBER}

#Email Config
spring.mail.host = ${MAIL_HOST}
spring.mail.port = ${MAIL_PORT}
spring.mail.username = ${MAIL_USER_NAME}
spring.mail.password = ${MAIL_PWD}
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true 

#OAuth Config
oauth.clientId= ${OAUTH_ID}

#
mail.emailId = ${MAIL_ID}

#RAZORPAY Config
razorpay.keyId=${RAZORPAY_KEY_ID}
razorpay.keySecret=${RAZORPAY_KEY_SECRET}